name: 🧠 Test Token Permissions

on:
  workflow_dispatch: {}

jobs:
  test:
    name: Test Token
    runs-on: ubuntu-latest
    
    steps:
      - name: Test workflow
        run: |
          echo "🧠 Testing updated GitHub token permissions"
          echo "✅ If you see this, the token has workflow scope!"
